# Terraform Provider release workflow.
name: Release

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Release version number'
        type: string
        required: true

env:
  CI_COMMIT_AUTHOR: SBGoods
  CI_COMMIT_EMAIL: email@example.com

permissions:
  contents: write

jobs:
  changelog-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changelog-version.outputs.version }}
    steps:
      - id: changelog-version
        run: echo "version=$(echo "${{ inputs.versionNumber }}" | cut -c 2-)" >> "$GITHUB_OUTPUT"
  go-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: go-version
        run: echo "version=$(cat ./.go-version)" >> "$GITHUB_OUTPUT"
  changelog:
    needs: changelog-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Batch changes
        uses: miniscruff/changie-action@v0
        with:
          version: latest
          args: batch ${{ needs.changelog-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge changes
        uses: miniscruff/changie-action@v0
        with:
          version: latest
          args: merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Git push changelog
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git add .
          git commit -a -m "Update changelog"
          git push
  release-tag:
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git push release tag
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git pull
          git tag "${{ inputs.versionNumber }}"
          git push origin "${{ inputs.versionNumber }}"
  release-notes:
    needs: [ changelog-version, changelog, release-tag ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.versionNumber }}
          fetch-depth: 0
      - name: Generate Release Notes
        run: |
          cd .changes
          sed -e "1{/# /d;}" -e "2{/^$/d;}" ${{ needs.changelog-version.outputs.version }}.md > release-notes.txt
      - uses: actions/upload-artifact@v3
        with:
          name: release-notes
          path: ./.changes/release-notes.txt
          retention-days: 1
  terraform-provider-release:
    name: 'Terraform Provider Release'
    needs: [go-version, release-notes]
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v2
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
      gpg-private-key-passphrase: '${{ secrets.PASSPHRASE }}'
    with:
      release-notes: true
      setup-go-version: '${{ needs.go-version.outputs.version }}'
      git-ref: '${{ inputs.versionNumber }}'
