# Terraform Provider release workflow.
name: Release

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Release version number'
        type: string
        required: true

# Releases need permissions to read and write the repository contents.
# GitHub considers creating releases and uploading assets as writing contents.
permissions:
  contents: write

jobs:
  set-changelog-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set Value
      - run: |
        echo "changelogVersion = $(echo ${{ inputs.versionNumber }} | cut -c 2-)" >> $GITHUB_ENV
  go-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: go-version
        run: echo "::set-output name=version::$(cat ./.go-version)"
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Batch changes
        uses: miniscruff/changie-action@v0
        with:
          version: latest
          args: batch ${{ env.changelogVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge changes
        uses: miniscruff/changie-action@v0
        with:
          version: latest
          args: merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Git push changelog
        run: |
          git config --global user.name "${{ secrets.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ secrets.CI_COMMIT_EMAIL }}"
          git add .
          git commit -a -m "Update changelog"
          git push
  release-tag:
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git push release tag
        run: |
          git config --global user.name "${{ secrets.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ secrets.CI_COMMIT_EMAIL }}"
          git pull
          git tag "${{ inputs.versionNumber }}"
          git push origin "${{ inputs.versionNumber }}"
  release-notes:
    needs: [ changelog, release-tag ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.versionNumber }}
          fetch-depth: 0
      - name: Generate Release Notes
        run: |
          cd .changes
          sed -e "1{/# /d;}" -e "2{/^$/d;}" ${{ env.changelogVersion }}.md > release-notes.txt
      - uses: actions/upload-artifact@v3
        with:
          name: release-notes
          path: ./.changes/release-notes.txt
          retention-days: 1
  terraform-provider-release:
    name: 'Terraform Provider Release'
    needs: [go-version, release-notes]
    uses: ./.github/workflows/community.yml
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
      gpg-private-key-passphrase: '${{ secrets.PASSPHRASE }}'
    with:
      release-notes: true
      setup-go-version: '${{ needs.go-version.outputs.version }}'
      #git-ref: '${{ inputs.versionNumber }}'
